// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1541573309);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1541573429);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1541573189);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1541573351);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181010142617");
user_pref("extensions.lastAppVersion", "60.2.1");
user_pref("extensions.lastPlatformVersion", "60.2.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "f9098501-725a-44c5-9afb-514234fe003");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.2.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "重要");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "工作");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "私人");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "待办");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "稍后");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "d21c4c79-9de5-4221-bbb2-606ceb5738a1");
user_pref("toolkit.telemetry.previousBuildID", "20181010142617");
user_pref("toolkit.telemetry.prompted", 2);
